### ISSUE TITLE
as organizing group I want to be notified about helpers that should be here on shifts

### ISSUE THREAD

**Issue by fkarg** [fkarg/UnifestBestellBot#20]
use the Engelsystem-API for that

**Comment by fkarg** [comment]
Implemented in commit 5bf6774 (closing #21 as well — same feature).

A background task in [`bot/digest.py`](https://github.com/fkarg/UnifestBestellBot/blob/unifest2026/src/unifestbestellbot/bot/digest.py) polls Engelsystem and DMs the orga group that handles `Helfer` requests (resolved via `route_category('Helfer')`, so a renamed orga still works). Configurable in `config.yaml`:

```yaml
shift_digest:
  enabled: false
  window_start: "18:00"
  window_end:   "02:00"
  check_interval_minutes: 5
  lookahead_minutes: 10
```

Disabled by default. Operational window is in local time and may wrap midnight. Each shift id is remembered once announced. Tests in `tests/test_digest.py` cover the window-arithmetic, formatting, in-window/out-of-window/already-announced cases, HTTP failure resilience, and the routing-to-renamed-orga path.
